Multi-Ledger Channel Example
perun-network/perun-examples pull request #11
Opened 2022-09-26 15:47 UTC by cryptphil

This PR adds an example of a multi-ledger example for transferring ERC20 tokens between two chains.
Is based on the code of the payment-channel example.

2022-10-05 10:18 UTC, matthiasgeihs requested changes

2022-10-05 10:18 UTC, matthiasgeihs commented on multiledger-channel/main.go
> +	chBob.SendPayment(42, client.ChainBIdx)
Payments are not a good example of a cross-chain application. Please modify to do a swap.

2022-10-05 10:18 UTC, matthiasgeihs commented on multiledger-channel/client/channel.go
> +type PaymentChannel struct {
Payments is not a good example. Better showcase Swaps.

2022-10-05 10:18 UTC, matthiasgeihs commented on multiledger-channel/client/channel.go
> +func (c PaymentChannel) SendPayment(amount float64, chainIndex int) {
Swap instead of payment.

2022-10-05 10:18 UTC, matthiasgeihs commented on multiledger-channel/client/handle.go
> +		// Check that our balance is only increasing for all currencies in the channel.
Need to update this for swaps.

2022-10-05 10:18 UTC, matthiasgeihs commented on multiledger-channel/go.mod
> +	github.com/perun-network/perun-eth-backend v0.0.0-20220803062824-a30444deaeb8
Why not use tagged version?

2022-10-05 10:18 UTC, matthiasgeihs commented on multiledger-channel/go.mod
> +	perun.network/go-perun v0.10.3
Why not used most recent tag?

2022-10-07 10:11 UTC, cryptphil commented on multiledger-channel/client/client.go
> +func (c *PaymentClient) OpenChannel(peer wire.Address, chainABalances, chainBBalances [2]float64) *PaymentChannel {
I wanted to make it more clear for the tutorial which balance array is for which asset (corresponding to a specific chain). But I'll change it to using `channel.Balances`.

2022-10-07 12:23 UTC, cryptphil commented on multiledger-channel/main.go
> +	chBob.SendPayment(42, client.ChainBIdx)
Modified to a swap.

2022-10-07 12:23 UTC, cryptphil commented on multiledger-channel/client/channel.go
> +func (c PaymentChannel) SendPayment(amount float64, chainIndex int) {
Modified to a swap.

2022-10-07 12:23 UTC, cryptphil commented on multiledger-channel/client/handle.go
> +		// Check that our balance is only increasing for all currencies in the channel.
Modified to a swap.

2022-10-07 12:52 UTC, cryptphil commented on multiledger-channel/go.mod
> +	github.com/perun-network/perun-eth-backend v0.0.0-20220803062824-a30444deaeb8
Fixed.

2022-10-07 12:52 UTC, cryptphil commented on multiledger-channel/go.mod
> +	perun.network/go-perun v0.10.3
Fixed.

2022-10-10 07:48 UTC, matthiasgeihs reviewed
The client struct is still called `PaymentClient` and the channel struct is still called `PaymentChannel`. I thought we agreed to change to `Swap...`?

2022-10-11 00:00 UTC, cryptphil commented
> The client struct is still called `PaymentClient` and the channel struct is still called `PaymentChannel`. I thought we agreed to change to `Swap...`?

No, that wasn't clear to me, but it is reasonable; I refactored it.

2022-10-11 07:01 UTC, matthiasgeihs approved these changes

2022-10-18 15:58 UTC, merged